version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/temp_audio:/app/temp_audio
      - ./gcp_creds.json:/app/gcp-creds.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-creds.json
    depends_on:
      - frontend
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: http://backend:8000

